<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>AssetDatabaseContributor</AssemblyName>
    <AssemblyTitle>Asset Database Contributor</AssemblyTitle>
    <Version>1.0.3</Version>
  </PropertyGroup>
  <Import Project="$([System.Environment]::GetEnvironmentVariable('CSII_TOOLPATH', 'EnvironmentVariableTarget.User'))\Mod.props" />
  <Import Project="$([System.Environment]::GetEnvironmentVariable('CSII_TOOLPATH', 'EnvironmentVariableTarget.User'))\Mod.targets" />
  <Import Project="..\..\ModsPersonal\StarQ.Shared\StarQ.Shared.projitems" Label="Shared" />
  <Import Project="..\..\ModsPersonal\StarQ.Shared\StarQ.Shared.props" />
  <Import Project="..\..\ModsPersonal\StarQ.Shared\StarQ.Shared.targets" />
</Project>
